Fix test problem and add valitator to model
Add 'javax.xml.bind' in pom.xml to prevent 'java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException' when test.
Import 'org.junit.Test' instead of 'org.junit.jupiter.api.Test' to avoid 'No runnable methods error' when test.
Cannot reproduce error 'Failed to load ApplicationContext'